- hosts: ubuntu
  become: true
  tasks:
    - name: install required packages for docker and docker-compose
      apt:
        pkg: [docker.io, python3-pip]
        force_apt_get: yes

    - name: install docker-compose using pip
      pip:
        name: docker-compose
        executable: pip3

    - name: docker-compose up
      docker_compose:
        project_name: nginx
        definition:
          version: '3'
          services:
            nginx:
              image: "nginx"
              ports:
                - "80:80"
                - "443:443"
        state: present
